import type { ScanResult, ScannedFile } from "@/types";

// ─── Sorting / Labels ─────────────────────────────────────────────────────────

const STATUS_ORDER: Record<string, number> = {
  "red-critical": 0,
  "red-fast":     1,
  "red-slow":     2,
  "yellow":       3,
  "green":        4,
};

const STATUS_LABELS: Record<string, string> = {
  "red-critical": "🚨 Critical",
  "red-fast":     "⚠️ Danger",
  "red-slow":     "🔴 Warning",
  "yellow":       "🟡 Caution",
  "green":        "🟢 Healthy",
};

function sortedFiles(files: ScannedFile[]): ScannedFile[] {
  return [...files].sort(
    (a, b) => STATUS_ORDER[a.health] - STATUS_ORDER[b.health] || b.lines - a.lines
  );
}

// ─── Markdown export ──────────────────────────────────────────────────────────

export function exportMarkdown(result: ScanResult): string {
  const sorted = sortedFiles(result.files);

  const summaryRows = Object.entries(STATUS_LABELS).map(([key, label]) => {
    const count = result.files.filter((f) => f.health === key).length;
    return `| ${label} | ${count} |`;
  });

  const fileRows = sorted.map((f, i) => {
    const resp = f.responsibilities.slice(0, 3).join(", ") || "—";
    const importCount = f.imports.length;
    return `| ${i + 1} | \`${f.path}\` | ${f.role} | ${f.lines.toLocaleString()} | ${STATUS_LABELS[f.health] ?? f.health} | ${importCount} | ${resp} |`;
  });

  return [
    `# ArchPulse Architecture Report`,
    ``,
    `**Project:** ${result.projectName}`,
    `**Path:** \`${result.rootPath}\``,
    `**Scanned:** ${new Date(result.scannedAt).toLocaleString()}`,
    `**Total Files:** ${result.totalFiles}`,
    `**Total Lines:** ${result.totalLines.toLocaleString()}`,
    ``,
    `---`,
    ``,
    `## Health Summary`,
    ``,
    `| Tier | Count |`,
    `|:-----|------:|`,
    ...summaryRows,
    ``,
    `---`,
    ``,
    `## File Audit (Sorted by Risk — Highest First)`,
    ``,
    `| # | File | Role | Lines | Health | Imports | Top Responsibilities |`,
    `|--:|:-----|:-----|------:|:-------|--------:|:--------------------|`,
    ...fileRows,
    ``,
    `---`,
    `*Generated by ArchPulse · ${new Date().toLocaleString()}*`,
  ].join("\n");
}

// ─── CSV export ───────────────────────────────────────────────────────────────

export function exportCSV(result: ScanResult): string {
  const sorted = sortedFiles(result.files);
  const header = `Rank,File,Role,Lines,Total Lines,Health,Imports,Responsibilities`;
  const rows = sorted.map((f, i) => {
    const resp = f.responsibilities.join(" | ").replace(/"/g, "'");
    return `${i + 1},"${f.path}","${f.role}",${f.lines},${f.totalLines},"${STATUS_LABELS[f.health] ?? f.health}",${f.imports.length},"${resp}"`;
  });
  return [header, ...rows].join("\n");
}

// ─── JSON export ──────────────────────────────────────────────────────────────

export function exportJSON(result: ScanResult): string {
  const sorted = sortedFiles(result.files);
  const payload = {
    meta: {
      project: result.projectName,
      path: result.rootPath,
      scannedAt: result.scannedAt,
      totalFiles: result.totalFiles,
      totalLines: result.totalLines,
      exportedAt: new Date().toISOString(),
    },
    files: sorted.map((f, i) => ({
      rank: i + 1,
      id: f.id,
      name: f.name,
      path: f.path,
      role: f.role,
      health: f.health,
      healthLabel: STATUS_LABELS[f.health] ?? f.health,
      lines: f.lines,
      totalLines: f.totalLines,
      imports: f.imports,
      responsibilities: f.responsibilities,
    })),
  };
  return JSON.stringify(payload, null, 2);
}

// ─── Download utility ─────────────────────────────────────────────────────────

export function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
